### ISSUE TITLE
[DEPR]: AnimationXBlock

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx-unsupported/AnimationXBlock#88]
### Proposal Date

2023-04-21

### Target Ticket Acceptance Date

2023-05-05

### Earliest Open edX Named Release Without This Functionality

Quince - 2023-10

### Rationale

To the best of my knowledge, this XBlock
* Is not working - https://github.com/openedx/AnimationXBlock/issues/87
* Is unused
* Is in a repo with no maintainer

### Removal

https://github.com/openedx/AnimationXBlock (the XBlock itself, the whole repo)

### Replacement

Assuming the assessment that this XBlock is currently unused is accurate, this should not require a replacement.

### Discourse Thread

https://discuss.openedx.org/t/deprecation-removal-animationxblock/9924

**Comment by brian-smith-tcril** [comment]
There have been no comments on https://discuss.openedx.org/t/deprecation-removal-animationxblock/9924 (just one like from Kyle), so I am moving this into the "Accepted" state.

**Comment by feanil** [comment]
This repo has been moved and will shortly be archived.
